---
- hosts: all
  become: yes

  # vars:
  #       - vars.yaml

  pre_tasks:
          - name: Update apt cache if needed
            apt: "update_cache=yes cache_valid_time=14400"
         
          # - debug: var=repo_stat
          - name: Check if the git repository exists
            stat: path=/opt/yolo
            register: repo_stat

          - name: Fetch the kitmikai/yolo GitHub repository
            git:
                    repo: https://github.com/kitmikai/yolo.git
                    dest: /opt/yolo
            when: not repo_stat.stat.exists

  tasks:
          # Install nodejs and npm on the client host
          - block:
                  - name: Install nodejs and npm on the client host 
                    apt:
                           state: present
                           name:
                                  - nodejs
                                  - npm
                  - name:  Check git repo folder exists.
                    stat: path=/opt/yolo/client
                    register: git_stat

                  - name: Copy the client directory to vagrant
                    command: mv /opt/yolo/client /home/vagrant
                    when: git_stat.stat.exists

                  - name: Install required modules in package.json
                    command: >
                            chdir=/home/vagrant/client
                            npm install

                  - name: Install PM2 (to run our client app)
                    command: >
                            chdir=/home/vagrant/client
                            npm install pm2 -g

                  - name: Spawn pm2 to become active
                    become: yes
                    become_user: vagrant
                    command: pm2 list

                  - name: Configure PM2 to start automatically on system bootup
                    command: pm2 startup

                  - name: Start the client app using PM2
                    become: yes
                    become_user: vagrant
                    command: >
                            chdir=/home/vagrant/client
                            pm2 start --name yolo_app npm -- start

                  - name: Save the list of process for automatic restart after a system reboot
                    command: pm2 save
            when: inventory_hostname == "client"

          # Install nodejs and npm on the backend host
          - block: 
                  - name: Install nodejs and npm on the backend host
                    apt:
                           state: present
                           name:
                                  - nodejs
                                  - npm

                  - name: Check git repo folder exists.
                    stat: path=/opt/yolo/backend
                    register: git_stat

                  - name: Copy the backend directory to vagrant home directory
                    command: mv /opt/yolo/backend /home/vagrant
                    when: git_stat.stat.exists

                  - name: Install required modules in package.json
                    command: >
                            chdir=/home/vagrant/backend
                            npm install

                  - name: Install PM2 (to run our app)
                    command: >
                            chdir=/home/vagrant/backend
                            npm install pm2 -g

                  - name: Configure PM2 to start automatically on system bootup
                    command: pm2 startup
                  
                  - name: Configure PM2 to start automatically on system bootup
                    command: pm2 list

                  - name: Start the backend using PM2
                    command: pm2 start --name yolo_app npm -- start

                  - name: Save the list of process for automatic restart after a system reboot
                    command: pm2 save
            when: inventory_hostname == "backend"
