---
- hosts: all
  become: yes

  # vars:
  #       - vars.yaml

  pre_tasks:
          - name: Update apt cache if needed
            apt: "update_cache=yes cache_valid_time=14400"
         
          # - debug: var=repo_stat
          - name: Check if the git repository exists
            stat: path=/opt/yolo
            register: repo_stat

          - name: Fetch the kitmikai/yolo GitHub repository
            git:
                    repo: https://github.com/kitmikai/yolo.git
                    dest: /opt/yolo
            when: not repo_stat.stat.exists

  tasks:
          # Install nodejs and npm on the client host
          - block:
                  - name: Install nodejs and npm on the client host 
                    apt:
                           state: present
                           name:
                                  - nodejs
                                  - npm
                                  - build-essential
                  - name:  Check git repo folder exists.
                    stat: path=/opt/yolo/client
                    register: git_stat

                  - name: Copy the client directory to vagrant
                    command: mv /opt/yolo/client /home/vagrant
                    when: git_stat.stat.exists

                  - name: Install required modules in package.json
                    command: >
                            chdir=/home/vagrant/client
                            npm install

                  - name: Run NPM for production
                    command: >
                            chdir=/home/vagrant/client
                            npm run build

                  - name: Install serve module
                    command: >
                            chdir=/home/vagrant/client
                            npm install -g serve

                  - name: Create nohup.out file
                    file:
                            path: "/home/vagrant/nohup.out"
                            state: touch

                  - name: Start the client app
                    shell:
                            " nohup serve -s build -l 3000 </dev/null >/dev/null 2>&1 & "
                    args: 
                            chdir: "/home/vagrant/client"

            when: inventory_hostname == "client"

          # Install nodejs and npm on the backend host
          - block: 
                  - name: Install nodejs and npm on the backend host
                    apt:
                           state: present
                           name:
                                  - nodejs
                                  - npm

                  - name: Check git repo folder exists.
                    stat: path=/opt/yolo/backend
                    register: git_stat

                  - name: Copy the backend directory to vagrant home directory
                    command: mv /opt/yolo/backend /home/vagrant
                    when: git_stat.stat.exists

                  - name: Install required modules in package.json
                    command: >
                            chdir=/home/vagrant/backend
                            npm install

                  - name: Install PM2 (to run our app)
                    command: >
                            chdir=/home/vagrant/backend
                            npm install pm2 -g

                  - name: Spawn PM2 to become active
                    become: yes
                    become_user: vagrant
                    command: pm2 list
                  
                  - name: Configure PM2 to start automatically on system bootup
                    command: pm2 startup

                  - name: Start the backend using PM2
                    become: yes
                    become_user: vagrant
                    command: >
                            chdir=/home/vagrant/backend
                            pm2 start --name yolo_app npm -- start

                  - name: Save the list of process for automatic restart after a system reboot
                    command: pm2 save
            when: inventory_hostname == "backend"

          # Install mongo on the db host
          - block: 
                  - name: Install required packages
                    apt:
                            state: present
                            name: 
                                   - dirmngr
                                   - gnupg
                                   - apt-transport-https
                                   - ca-certificates
                                   - software-properties-common

                  - name: Import public GPG key for the latest stable version of MongoDB
                    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=9DA31620334BD75D9DCB49F368818C72E52529D4 state=present

                  - name: Add MongoDB repository
                    apt_repository: repo='deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse' state=present

                  - name: Update cache
                    apt: "update_cache=yes"

                  - name: Install MongoDB
                    apt: pkg=mongodb-org state=latest update_cache=yes

                  - name: Start MongoDB
                    service: name=mongod state=started


            when: inventory_hostname == "mongodb"
